[sinks.influxdb_logs]
title = "InfluxDB Logs"
noun = "InfluxDB"
beta = true
common = false
delivery_guarantee = "at_least_once"
description = """\
[InfluxDB][urls.influxdb] is an open-source time series database developed by \
InfluxData. It is written in Go and optimized for fast, high-availability \
storage and retrieval of time series data in fields such as operations \
monitoring, application metrics, Internet of Things sensor data, and \
real-time analytics.\
"""
egress_method = "batching"
features = [
  "Send structured logs to InfluxDB v1 or v2.",
  "Batch data to maximize throughput.",
  "Automatically retry failed requests, with backoff.",
  "Automatically aggregate metrics at the edge for improved performance.",
]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
requirements = {}
service_providers = ["InfluxData"]
write_to_description = "[InfluxDB][urls.influxdb] using [v1][urls.influxdb_http_api_v1] or [v2][urls.influxdb_http_api_v2] HTTP API"

<%= render(
  "_partials/fields/_component_options.toml",
  groups: ["v1", "v2"],
  name: "influxdb_logs",
  type: "sink"
) %>

<%= render(
  "_partials/fields/_batch_options.toml",
  common: false,
  groups: ["v1", "v2"],
  max_bytes: 1049000,
  max_events: nil,
  namespace: "sinks.influxdb_logs.options",
  timeout_secs: 1
) %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.influxdb_logs.options",
  common: false,
  groups: ["v1", "v2"],
) %>

<%= render(
  "_partials/fields/_request_options.toml",
  namespace: "sinks.influxdb_logs.options",
  common: false,
  groups: ["v1", "v2"],
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 5,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 60
) %>

<%= render("_partials/fields/_encoding_options.toml",
  namespace: "sinks.influxdb_logs.options",
  encodings: [],
  groups: ["v1", "v2"],
) %>

[sinks.influxdb_logs.options.endpoint]
type = "string"
common = true
examples.all = ["http://localhost:8086/"]
examples.v1 = ["https://us-west-2-1.aws.cloud1.influxdata.com"]
examples.v2 = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
groups = ["v1", "v2"]
required = true
sort = 1
description = "InfluxDB endpoint to send metrics to."

[sinks.influxdb_logs.options.org]
type = "string"
category = "Auth"
common = true
examples = ["my-org", "33f2cff0a28e5b63"]
groups = ["v2"]
required = true
description = "Specifies the destination organization for writes into InfluxDB 2."

[sinks.influxdb_logs.options.bucket]
type = "string"
common = true
examples = ["vector-bucket", "4d2225e4d3d49f75"]
groups = ["v2"]
required = true
description = "The destination bucket for writes into InfluxDB 2."

[sinks.influxdb_logs.options.token]
type = "string"
category = "Auth"
common = true
examples = ["${INFLUXDB_TOKEN}", "ef8d5de700e7989468166c40fc8a0ccd"]
groups = ["v2"]
required = true
description = "[Authentication token][urls.influxdb_authentication_token] for InfluxDB 2."

[sinks.influxdb_logs.options.database]
type = "string"
common = true
examples = ["vector-database", "iot-store"]
groups = ["v1"]
required = true
description = "Sets the target database for the write into InfluxDB 1."

[sinks.influxdb_logs.options.consistency]
type = "string"
category = "Persistence"
common = true
examples = ["any", "one", "quorum", "all"]
groups = ["v1"]
required = false
description = "Sets the write consistency for the point for InfluxDB 1."

[sinks.influxdb_logs.options.retention_policy_name]
type = "string"
category = "Persistence"
common = true
examples = ["autogen", "one_day_only"]
groups = ["v1"]
required = false
description = "Sets the target retention policy for the write into InfluxDB 1."

[sinks.influxdb_logs.options.username]
type = "string"
category = "Auth"
common = true
examples = ["todd", "vector-source"]
groups = ["v1"]
required = false
description = "Sets the username for authentication if you’ve enabled authentication for the write into InfluxDB 1."

[sinks.influxdb_logs.options.password]
type = "string"
category = "Auth"
common = true
examples = ["${INFLUXDB_PASSWORD}", "influxdb4ever"]
groups = ["v1"]
required = false
description = "Sets the password for authentication if you’ve enabled authentication for the write into InfluxDB 1."

[sinks.influxdb_logs.options.namespace]
type = "string"
common = true
examples = ["service"]
groups = ["v1", "v2"]
required = true
sort = 1
description = "A prefix that will be added to all metric names."

[sinks.influxdb_logs.options.tags]
type = "[string]"
groups = ["v1", "v2"]
examples = [["field1", "parent.child_field"]]
required = false
description = """\
A set of additional fields that will be attached to each LineProtocol as a tag. \

Note: If the set of tag values has high cardinality this also \
increase cardinality in InfluxDB.\
"""
