description = """\
[Amazon CloudWatch][urls.aws_cloudwatch] is a monitoring and management \
service that provides data and actionable insights for AWS, hybrid, and \
on-premises applications and infrastructure resources. With CloudWatch, you \
can collect and access all your performance and operational data in form of \
logs and metrics from a single platform.\
"""
