description = """\
[Datadog][urls.datadog] is a monitoring service for cloud-scale applications, \
providing monitoring of servers, databases, tools, and services, through a \
SaaS-based data analytics platform.\
"""
