description = """\
[Stackdriver][urls.gcp_stackdriver] is Google Cloud's embedded observability \
suite designed to monitor, troubleshoot, and improve cloud infrastructure, \
software, and application performance. Stackdriver enables you to efficiently \
build and run workloads, keeping applications performant and available.\
"""
