description = """\
[Kubernetes][urls.kubernetes] is a system for managing containerized \
applications across a cluster of nodes. In simple terms, you have a group of \
machines (e.g. VMs) and containerized applications (e.g. Dockerized \
applications), and Kubernetes will help you to easily manage those apps across \
those machines. Because Kubernetes is very abstract its criticaly important \
that you collect the appropriate logs and metrics to monitor and oobserve \
Kubernetes activity.\
"""
