description = """\
The [Splunk HTTP Event Collector (HEC)][urls.splunk_hec] is a fast and \
efficient way to send data to Splunk Enterprise and Splunk Cloud. Notably, \
HEC enables you to send data over HTTP (or HTTPS) directly to Splunk \
Enterprise or Splunk Cloud from your application.\
"""
