description = """\
[Syslog][urls.syslog] stands for System Logging Protocol and is a standard \
protocol used to send system log or event messages to a specific server, \
called a syslog server. It is primarily used to collect various device logs \
from several different machines in a central location for monitoring and \
review.\
"""
