apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-daemonset-managed-config
data:
  managed.toml: |
    # Configuration for vector.
    # Docs: https://vector.dev/docs/

    # Configure the controlled by the deployment.
    data_dir = "/vector-data-dir"

    # Ingest logs from Kubernetes.
    [sources.kubernetes]
        type = "kubernetes"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  labels:
    k8s-app: vector
spec:
  selector:
    matchLabels:
      name: vector
  template:
    metadata:
      labels:
        name: vector
    spec:
      containers:
        - name: vector
          image: timberio/vector:latest-alpine
          imagePullPolicy: Always
          args:
            - --config
            - /etc/vector/*.toml
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: var-log
              mountPath: /var/log/
              readOnly: true
            - name: var-lib
              mountPath: /var/lib/
              readOnly: true
            - name: data-dir
              mountPath: /vector-data-dir/
            - name: config-dir
              mountPath: /etc/vector/
              readOnly: true
      tolerations:
        # This toleration is to have the daemonset runnable on master nodes.
        # Remove it if your masters can't run pods.
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      volumes:
        # Log directory.
        - name: var-log
          hostPath:
            path: /var/log/
        # Docker and containerd log files in Kubernetes are symlinks to this folder.
        - name: var-lib
          hostPath:
            path: /var/lib/
        # Vector will store it's data here.
        - name: data-dir
          hostPath:
            path: /var/lib/vector/
        # Vector config files.
        - name: config-dir
          projected:
            sources:
              - configMap:
                  name: vector-daemonset-managed-config
                  optional: true
              - configMap:
                  name: vector-config
                  optional: true
              - secret:
                  name: vector-config
                  optional: true
