# Permissions to use Kubernetes API.
# Requires that RBAC authorization is enabled.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector
subjects:
  - kind: ServiceAccount
    name: default
    namespace: vector
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
