[data_model.log.schema.host]
type = "string"
examples = ["my.host.com"]
required = false
description = """\
Represents the originating host of the log. This is automatically set within \
select [sources][docs.sources] if the key does not exist. Change this field \
name via the [global `host_key` option][docs.reference.global-options#host_key] \
or the source-level `host_key` option for relevant sources.\
"""

[data_model.log.schema.message]
type = "string"
examples = ["<13>Feb 13 20:07:26 74794bfb6795 root[8539]: i am foobar"]
required = true
description = """\
Represents the log message. Change this field name via the \
[global `message_key` option][docs.reference.global-options#message_key] or the \
source-level `message_key` option for relevant sources.
"""

[data_model.log.schema.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
required = true
description = """\
A normalized [Rust DateTime struct][urls.rust_date_time] in UTC. Change this \
field name via the \
[global `timestamp_key` option][docs.reference.global-options#message_key] or \
the source-level `timestamp_key` option for relevant sources.
"""

[data_model.log.schema.source_type]
type = "string"
examples = ["file", "socket", "http"]
required = false
description = """\
The official `type` of [Vector's source component][docs.sources] from which \
the log originates. Change this field name via the \
[global `source_type_key` option][docs.reference.global-options#source_type_key] \
or the source-level `source_type_key` option for relevant sources.
"""

[data_model.log.schema."`[custom-key]`"]
type = "*"
examples = [
  {my-key = "my-value"},
  {parent.child = "child-value"}
]
required = false
description = """\
In addition to the defined fields, a log event can have any number of \
additional fields. This includes nested fields.
"""
