# Downloads
#
# Downloads represent actual download artifacts available on
# https://packages.timber.io/vector

[installation.downloads.x86_64-unknown-linux-musl-tar-gz]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-unknown-linux-musl.tar.gz"
file_type = "tar.gz"
os = "Linux"
title = "Linux (x86_64)"
type = "archive"

[installation.downloads.aarch64-unknown-linux-musl-tar-gz]
available_on_latest = true
available_on_nightly = true
arch = "ARM64"
file_name = "vector-aarch64-unknown-linux-musl.tar.gz"
file_type = "tar.gz"
os = "Linux"
title = "Linux (ARM64)"
type = "archive"

[installation.downloads.armv7-unknown-linux-musleabihf-tar-gz]
available_on_latest = true
available_on_nightly = true
arch = "ARMv7"
file_name = "vector-armv7-unknown-linux-musleabihf.tar.gz"
file_type = "tar.gz"
os = "Linux"
title = "Linux (ARMv7)"
type = "archive"

[installation.downloads.x86_64-apple-darwin-tar-gz]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-apple-darwin.tar.gz"
file_type = "tar.gz"
os = "MacOS"
title = "MacOS (x86_64)"
type = "archive"

[installation.downloads.x86_64-pc-windows-msvc-zip]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64-pc-windows-msvc.zip"
file_type = "zip"
os = "Windows"
title = "Windows (x86_64, 7+)"
type = "archive"

[installation.downloads.x64-msi]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x64.msi"
file_type = "msi"
os = "Windows"
package_manager = "msi"
title = "Windows (x86_64, 7+)"
type = "package"

[installation.downloads.amd64-deb]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-amd64.deb"
file_type = "deb"
os = "Linux"
package_manager = "dpkg"
title = "Deb (x86_64)"
type = "package"

[installation.downloads.arm64-deb]
available_on_latest = true
available_on_nightly = true
arch = "ARM64"
file_name = "vector-arm64.deb"
file_type = "deb"
os = "Linux"
package_manager = "dpkg"
title = "Deb (ARM64)"
type = "package"

[installation.downloads.armhf-deb]
available_on_latest = true
available_on_nightly = true
arch = "ARMv7"
file_name = "vector-armhf.deb"
file_type = "deb"
os = "Linux"
package_manager = "dpkg"
title = "Deb (ARMv7)"
type = "package"

[installation.downloads.x86_64-rpm]
available_on_latest = true
available_on_nightly = true
arch = "x86_64"
file_name = "vector-x86_64.rpm"
file_type = "rpm"
os = "Linux"
package_manager = "rpm"
title = "RPM (x86_64)"
type = "package"

[installation.downloads.aarch64-rpm]
available_on_latest = true
available_on_nightly = true
arch = "ARM64"
file_name = "vector-aarch64.rpm"
file_type = "rpm"
os = "Linux"
package_manager = "rpm"
title = "RPM (ARM64)"
type = "package"

[installation.downloads.armv7hl-rpm]
available_on_latest = true
available_on_nightly = true
arch = "ARMv7"
file_name = "vector-armv7hl.rpm"
file_type = "rpm"
os = "Linux"
package_manager = "rpm"
title = "RPM (ARMv7)"
type = "package"
