[installation.package_managers.dpkg]
title = "DPKG"
archs = ["x86_64", "ARM64", "ARMv7"]
interfaces = ["dpkg"]
strategies = [
  {name = "daemon", source = "journald"},
]

[installation.package_managers.homebrew]
title = "Homebrew"
archs = ["x86_64"]
interfaces = ["homebrew"]
strategies = [
  {name = "daemon", source = "file"},
]

[installation.package_managers.msi]
title = "MSI"
interfaces = ["msi"]
archs = ["x86_64"]
strategies = [
  {name = "daemon", source = "file"},
]

[installation.package_managers.nix]
title = "Nix"
interfaces = ["nix"]
archs = ["x86_64"]
strategies = [
  {name = "daemon", source = "journald"},
]

[installation.package_managers.rpm]
title = "RPM"
interfaces = ["rpm"]
archs = ["x86_64"]
strategies = [
  {name = "daemon", source = "journald"},
]
