# Strategies
#
# Strategies represent deployment strategies. Operating systems and platforms
# must specify which strategies they support.

[installation.strategies.daemon]
title = "Daemon"

[installation.strategies.sidecar]
title = "Sidecar"

[installation.strategies.service]
title = "Service"
