version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "hoverbear"
    default_assignees:
      - "hoverbear"
    default_labels:
      - "domain: dependencies"
    # https://dependabot.com/docs/config-file/#version_requirement_updates
    version_requirement_updates: "off" # We should consider switching this to "auto"
    commit_message:
      prefix: "chore(deps)"
