[guides.advanced]
title = "Advanced"
series = false
description = """\
Go beyond the basics, become a Vector pro, and extract the full potential of Vector.\
"""

[guides.getting-started]
title = "Getting Started"
series = true
description = """\
Take Vector from zero to production in under 10 minutes.\
"""

[guides.integrate]
title = "Integrate"
series = false
description = """\
Targeted guides for integrating platforms, data sources, and data destinations.\
"""
