[options.data_dir]
type = "string"
default = "/var/lib/vector/"
examples = ["/var/lib/vector", "/var/local/lib/vector/", "/home/user/vector/"]
description = """\
The directory used for persisting Vector state, such as on-disk buffers, \
file checkpoints, and more. Please make sure the Vector project has write \
permissions to this dir.\
"""

[options.log_schema]
type = "table"
description = """\
The default log schema that all Vector components operate on. See the \
[log data model page][docs.data-model.log] for more info.
"""

[options.log_schema.children.host_key]
type = "string"
default = "host"
examples = ["host", "@host", "instance", "machine"]
description = """\
The key used to hold the log host. See the \
[log data model page][docs.data-model.log#host] for more info.\
"""

[options.log_schema.children.message_key]
type = "string"
default = "message"
examples = ["message", "@message", "msg"]
description = """\
The key used to hold the log message. See the \
[log data model page][docs.data-model.log#message] for more info.\
"""

[options.log_schema.children.timestamp_key]
type = "string"
default = "timestamp"
examples = ["timestamp", "@timestamp", "datetime"]
description = """\
The key used to represent when the log was generated. See the \
[log data model page][docs.data-model.log#timestamp] for more info.\
"""

[options.log_schema.children.source_type_key]
type = "string"
default = "source_type"
examples = ["source_type", "@source_type", "src_ty"]
description = """\
The key used to hold the log source type. See the \
[log data model page][docs.data-model.log#source_type] for more info.\
"""
