[[team]]
id = "alex"
avatar = "https://github.com/a-rodin.png"
github = "https://github.com/a-rodin"
keybase = "https://keybase.io/arodin"
name = "Alexander"
bio = """\
Alexander is a Senior Engineer at <a href="https://timber.io">Timber.io</a> \
and a member of the <a href="/community#team">core Vector team</a>. He created \
<a href="https://alexanderrodin.com/qstardict">QStarDict</a>, a dictionary \
application written in C++.\
"""

[[team]]
id = "ana"
avatar = "https://github.com/hoverbear.png"
github = "https://github.com/hoverbear"
keybase = "https://keybase.io/hoverbear"
twitter = "https://twitter.com/a_hoverbear"
name = "Ana"
bio = """\
Ana is the proprietor of <a href="https://hoverbear.org/">Hoverbear \
Consulting</a>, and <a href="https://timber.io">Timber.io</a> supports her \
work as a <a href="/community#team">core Vector team</a> member. She is \
focused on building capacity within the Rust ecosystem and her local community. \
A frequent speaker, teacher, and mentor, she was a founding \
organizer of <a href="https://rustfest.eu/">RustFest</a>, \
<a href="https://rustcon.asia/">RustCon Asia</a>, and \
<a href="https://www.rust-belt-rust.com/">Rust Belt Rust</a>.
"""

[[team]]
id = "ashley"
avatar = "https://github.com/Jeffail.png"
github = "https://github.com/Jeffail"
keybase = "https://keybase.io/jeffail"
twitter = "https://twitter.com/jeffail"
name = "Ashley"
bio = """\
Ashley is a Principal Engineer at <a href="https://timber.io">Timber.io</a> \
and member of the <a href="/community#team">core Vector team</a>. He created \
<a href="https://github.com/Jeffail/benthos">Benthos stream processor</a>, a \
popular stream processor written Go.\
"""

[[team]]
id = "ben"
avatar = "https://github.com/binarylogic.png"
github = "https://github.com/binarylogic"
keybase = "https://keybase.io/binarylogic"
twitter = "https://twitter.com/binarylogic"
name = "Ben"
bio = """\
Ben is the CTO/Co-Founder at <a href="https://timber.io">Timber.io</a> and a \
member of the <a href="/community#team">core Vector team</a>. He is an \
open-source veteran, creating \
<a href="https://github.com/binarylogic/authlogic">Authlogic</a> over 15 years \
ago before helping to launch Vector.\
"""

[[team]]
id = "bruce"
avatar = "https://github.com/bruceg.png"
github = "https://github.com/bruceg"
name = "Bruce"

[[team]]
id = "kruno"
avatar = "https://github.com/ktff.png"
github = "https://github.com/ktff"
name = "Kruno"

[[team]]
id = "lucio"
avatar = "https://github.com/LucioFranco.png"
github = "https://github.com/LucioFranco"
keybase = "https://keybase.io/luciofranco"
twitter = "https://twitter.com/lucio_d_franco"
name = "Lucio"

[[team]]
id = "luke"
avatar = "https://github.com/lukesteensen.png"
github = "https://github.com/lukesteensen"
keybase = "https://keybase.io/lukesteensen"
twitter = "https://twitter.com/lukesteensen"
name = "Luke"
bio = """\
Luke is a Senior Engineer at <a href="https://timber.io">Timber.io</a> \
and member of the <a href="/community#team">core Vector team</a>. Before \
Timber Luke was an engineer at Braintree, working on parts of their \
observability pipeline.\
"""

[[team]]
id = "mike"
avatar = "https://github.com/MOZGIII.png"
github = "https://github.com/MOZGIII"
keybase = "https://keybase.io/MOZGIII"
twitter = "https://twitter.com/MOZGIII"
name = "Mike"

[[team]]
id = "vic"
avatar = "https://github.com/vector-vic.png"
github = "https://github.com/vector-vic"
name = "Vic"
