#
# Subdomains
#

[[redirects]]
  from = "https://vector-project.netlify.com/*"
  to = "https://vector.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://chat.vector.dev/*"
  to = "https://gitter.im/timberio-vector/community"
  status = 302
  force = true

[[redirects]]
  from = "https://roadmap.vector.dev/*"
  to = "https://github.com/timberio/vector/issues/1538"
  status = 302
  force = true

[[redirects]]
  from = "https://sh.vector.dev/*"
  to = "http://sh.vector.dev.s3-website-us-east-1.amazonaws.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://test-results.vector.dev/*"
  to = "http://test-results.vector.dev.s3-website-us-east-1.amazonaws.com/:splat"
  status = 200
  force = true

#
# Old docs site
#

[[redirects]]
  from = "https://docs.vector.dev/v/:version/*"
  to = "https://docs.vector.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/correctness"
  to = "https://vector.dev/#correctness"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/performance"
  to = "https://vector.dev/#performance"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/administration"
  to = "https://vector.dev/docs/administration/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/administration/stopping"
  to = "https://vector.dev/docs/administration/process-management/#stopping"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/administration/reloading"
  to = "https://vector.dev/docs/administration/process-management/#reloading"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/administration/starting"
  to = "https://vector.dev/docs/administration/process-management/#starting"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/administration/*"
  to = "https://vector.dev/docs/administration/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/configuration"
  to = "https://vector.dev/docs/setup/configuration/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/usage/configuration/*"
  to = "https://vector.dev/docs/reference/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.vector.dev/*"
  to = "https://vector.dev/docs/:splat"
  status = 301
  force = true

#
# Internal redirects
#
# Sorted by the `from` attribute.
#

[[redirects]]
  from = "/blog/arm-support-on-linux/"
  to = "/highlights/2019-11-19-arm-support-on-linux/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/custom-dns/"
  to = "/highlights/2019-12-13-custom-dns/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/ec2-metadata/"
  to = "/highlights/2019-12-16-ec2-metadata/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/kubernetes-source-alpha/"
  to = "/highlights/2019-12-14-kubernetes-source-alpha/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/prometheus-source/"
  to = "/highlights/2020-01-07-prometheus-source/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tags/announcement/"
  to = "/blog/tags/type-announcement/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/unit-testing-vector-config-files/"
  to = "/highlights/2019-11-25-unit-testing-vector-config-files/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/windows-support/"
  to = "/highlights/2019-11-21-windows-support/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/"
  to = "/docs/about/what-is-vector/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/about/correctness"
  to = "https://vector.dev/#correctness"
  status = 301
  force = true

[[redirects]]
  from = "/docs/about/performance"
  to = "https://vector.dev/#performance"
  status = 301
  force = true

[[redirects]]
  from = "/docs/components/*"
  to = "/docs/reference/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/docs/configuration"
  to = "/docs/setup/configuration/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/deployment/roles/"
  to = "/docs/setup/deployment/strategies/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/deployment/roles/agent/"
  to = "/docs/setup/deployment/strategies/#daemon"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/deployment/roles/service/"
  to = "/docs/setup/deployment/strategies/#service"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/getting-started"
  to = "/guides/getting-started/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/"
  to = "/guides/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/advanced-configs/"
  to = "/guides/advanced/managing-complex-configs/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/getting-started/"
  to = "/guides/getting-started/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/troubleshooting"
  to = "/guides/getting-started/troubleshooting/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/unit-testing"
  to = "/guides/advanced/unit-testing/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/containers/"
  to = "/docs/setup/installation/platforms/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/containers/docker/"
  to = "/docs/setup/installation/platforms/docker"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/deployment/roles/agent/"
  to = "/docs/setup/installation/deployment/strategies/#daemon"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/deployment/roles/service/"
  to = "/docs/setup/installation/deployment/strategies/#service"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/package-managers/yum"
  to = "/docs/setup/installation/package-managers/rpm/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sinks/s3"
  to = "/docs/reference/sinks/aws_s3/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sinks/tcp/"
  to = "/docs/reference/sinks/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sources/tcp/"
  to = "/docs/reference/sources/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sources/udp/"
  to = "/docs/reference/sources/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/usage/*"
  to = "/docs/administration/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/download/"
  to = "/releases/latest/download/"
  status = 302
  force = true

[[redirects]]
  from = "/mailing_list/"
  to = "/community/"
  status = 301
  force = true

[[redirects]]
  from = "/releases/"
  to = "/releases/latest/download/"
  status = 302
  force = true

[[redirects]]
  from = "/releases/nightly/"
  to = "/releases/nightly/download/"
  status = 301
  force = true
