name: Environment Suite

on:
  push:
    branches:
      - master

env:
  VERBOSE: true
  ENVIRONMENT_UPSTREAM: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}

jobs:
  publish-new-environment:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_AUTOBUILD: true
    steps:
      - run: docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: make environment-prepare
      - run: docker push docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
